export const tempData = {
  report: {
    id: 15,
    created_at: '2023-09-22T15:53:14.266Z',
    author: {
      avatar: '/temp/avatar.png',
      first_name: 'Islam',
      last_name: 'Nazaraliev',
    },
    pic1: '/temp/before.png',
    pic2: '/temp/after.png',
  },
  user: {
    id: 1,
    company_id: 2,
    email: 'test@gmail.com',
    phone: '77074660324',
    first_name: 'Anastasya',
    last_name: 'Litvinenko',
    position: 'test',
    avatar: '/temp/avatar.png',
    description: 'test test test test',
    price_plan_id: 3,
  },
  folderImg: '/temp/folder-image.png',
  notifications: {
    count: 41,
  },
  folders: [
    {
      id: 1,
      folder_id: 1,
      name: 'Kamchatka',
      company_id: 1,
      slug: 'test',
      description: 'test test test',
      parent: 2,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: true,
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: [
        '/temp/test-folder.png',
        '/temp/test-folder-2.png',
        '/temp/test-folder.png',
      ],
      project_info: {
        grain: 1.25,
        area: 1.5,
        orientation: 2,
        point: 1,
      },
    },
    {
      id: 2,
      folder_id: 2,
      name: 'Kamchatka 2',
      company_id: 2,
      slug: 'test2',
      description: 'test test test',
      parent: 2,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: false,
      archived: true,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: ['/temp/test-folder.png'],
      project_info: {
        grain: 1.25,
        area: 1.5,
        orientation: 2,
        point: 1,
      },
    },
    {
      id: 3,
      folder_id: 3,
      name: 'Kamchatka 3',
      company_id: 3,
      slug: 'test',
      description: 'test test test',
      parent: 4,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: false,
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: [
        '/temp/test-folder.png',
        '/temp/test-folder-2.png',
        '/temp/test-folder.png',
      ],
      project_info: {
        grain: 0.25,
        area: 2.5,
        orientation: 1,
        point: 4,
      },
    },
    {
      id: 4,
      folder_id: 4,
      name: 'Kamchatka 4',
      company_id: 4,
      slug: 'test',
      description: 'test test test',
      parent: 5,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: false,
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: [],
      project_info: {
        grain: 0.25,
        area: 2.5,
        orientation: 1,
        point: 4,
      },
    },
  ],
  pricePlans: [
    {
      id: 1,
      slug: 'Popular',
      title: 'Basic',
      content: 'Fishtext is used by designers, planners typography in action.',
      price: 10000,
    },
    {
      id: 2,
      slug: 'Popular',
      title: 'Basic',
      content: 'Fishtext is used by designers, planners typography in action.',
      price: 10000,
    },
    {
      id: 3,
      slug: 'Popular',
      title: 'Basic',
      content: 'Fishtext is used by designers, planners typography in action.',
      price: 10000,
    },
  ],
  projects: [
    {
      folder_id: 1,
      title: 'Kamchatka',
      content:
        // eslint-disable-next-line max-len
        'Fishtext is used by designers, planners, and frontenders when they need to quickly populate mockups or prototypes with content. Fishtext is used by designers, planners, and frontenders when they need to quickly populate mockups or prototypes with content.',
      lat: 2,
      lng: 1,
      industry: 'test',
      location: 'test',
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      slug: 'test-slug-project',
      top: false,
      reportsCount: 5,
      project_info: {
        grain: 2,
        area: 1,
        orientation: 4,
        point: 1,
      },
    },
    {
      folder_id: 2,
      title: 'Kamchatka 2',
      content:
        // eslint-disable-next-line max-len
        '2 Fishtext is used by designers, planners, and frontenders when they need to quickly populate mockups or prototypes with content. Fishtext is used by designers, planners, and frontenders when they need to quickly populate mockups or prototypes with content.',
      lat: 1,
      lng: 2,
      industry: 'test 2',
      location: 'test 1',
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      slug: 'test-2-project',
      top: false,
      reportsCount: 2,
      project_info: {
        grain: 2,
        area: 1,
        orientation: 4,
        point: 1,
      },
    },
  ],
  reports: [
    {
      id: 1,
      folder_id: 1,
      name: 'Kamchatka',
      company_id: 1,
      slug: 'test',
      description: 'test test test',
      parent: 2,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: true,
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: [
        '/temp/test-folder.png',
        '/temp/test-folder-2.png',
        '/temp/test-folder.png',
      ],
      project_info: {
        grain: 1.25,
        area: 1.5,
        orientation: 2,
        point: 1,
      },
    },
    {
      id: 2,
      folder_id: 2,
      name: 'Kamchatka 2',
      company_id: 2,
      slug: 'test2',
      description: 'test test test',
      parent: 2,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: false,
      archived: true,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: ['/temp/test-folder.png'],
      project_info: {
        grain: 1.25,
        area: 1.5,
        orientation: 2,
        point: 1,
      },
    },
    {
      id: 3,
      folder_id: 3,
      name: 'Kamchatka 3',
      company_id: 3,
      slug: 'test',
      description: 'test test test',
      parent: 4,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: false,
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: [
        '/temp/test-folder.png',
        '/temp/test-folder-2.png',
        '/temp/test-folder.png',
      ],
      project_info: {
        grain: 0.25,
        area: 2.5,
        orientation: 1,
        point: 4,
      },
    },
    {
      id: 4,
      folder_id: 4,
      name: 'Kamchatka 4',
      company_id: 4,
      slug: 'test',
      description: 'test test test',
      parent: 5,
      level_num: 1,
      order_num: 2,
      visible: 0,
      top: false,
      archived: false,
      created_at: '2023-09-22T15:53:14.266Z',
      project_images: [],
      project_info: {
        grain: 0.25,
        area: 2.5,
        orientation: 1,
        point: 4,
      },
    },
  ],
};
